### PR TITLE
Move build to rattler-build

### PR DESCRIPTION
**Pull request by luizirber**
Follow https://prefix.dev/blog/rattler_build_on_conda_forge to use rattler-build.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by luizirber** [comment]
@conda-forge-admin, please rerender

**Comment by luizirber** [comment]
@conda-forge-admin, please rerender

**Comment by luizirber** [comment]
@conda-forge-admin, please rerender

**Comment by luizirber** [comment]
@conda-forge-admin, please rerender

**Comment by luizirber** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
I pushed the fix which was just not to skip over _all_ variants :)

The problem in your case was that the `skip` condition was wrong (`<py310` always evaluated to `true`, but you wanted to use `match(python, "<3.10")`).

**Comment by wolfv** [comment]
Hi @luizirber thank you for testing and I am super excited!

It looks like we're hitting two problems now, one of those looks like a rattler-build problem: when testing `linux-aarch64` and `linux-ppc64le` we are trying to find `sourmash` for the `linux-64` platform (which is _not_ the target-platform). I'll have a look and will try to fix this today! 

For the Windows failure, I am not sure exactly what's going on yet. The next release also adds `@echo on` to Windows scripts so it might be easier to understand going forward.

**Comment by wolfv** [comment]
OK, fix for linux-aarch64 and linux-ppc64le tests is done :)

Let's check Windows again once we have the latest release. Sorry for the hiccups :)

**Comment by luizirber** [comment]
> Hi @luizirber thank you for testing and I am super excited!

me too =]
 
> It looks like we're hitting two problems now, one of those looks like a rattler-build problem: when testing `linux-aarch64` and `linux-ppc64le` we are trying to find `sourmash` for the `linux-64` platform (which is _not_ the target-platform). I'll have a look and will try to fix this today!

:tada: 

> For the Windows failure, I am not sure exactly what's going on yet. The next release also adds `@echo on` to Windows scripts so it might be easier to understand going forward.

the windows build is overly complicated, I was looking into the [polars feedstock](https://github.com/conda-forge/polars-feedstock/blob/c8ef1a8a318bc4086887bf7b1205c8d00bb32601/recipe/meta.yaml#L35) and wondering if using
```
  build:
    - posix                               # [build_platform == "win-64"]
```
and reusing `build.sh` is simpler going forward

**Comment by wolfv** [comment]
I think you can rerun the build now and the two linux ones should work :)

**Comment by wolfv** [comment]
@luizirber - sorry for not noticing earlier, but we renamed `bld.bat` to `build.bat`. 

I think there are three things we could improve:

- automatically rename `bld.bat` to `build.bat` with conda-recipe-manager
- warn when there is no script in rattler-build 
- continue to support `bld.bat` but show a deprecation warning or something like that

Would love to hear your opinion!

**Comment by luizirber** [comment]
> @luizirber - sorry for not noticing earlier, but we renamed `bld.bat` to `build.bat`.

Oh! That was an easy fix :sweat_smile: 

> I think there are three things we could improve:
> 
>     * automatically rename `bld.bat` to `build.bat` with conda-recipe-manager
>     * warn when there is no script in rattler-build 
>     * continue to support `bld.bat` but show a deprecation warning or something like that

I like both 1 and 2, and maybe a mix of 2 and 3 where it warns it found a `bld.bat` and it should be renamed to `build.bat`, and then fails.

**Pull request merged**
